CREATE DATABASE SportFlowDB;
USE SportFlowDB;

CREATE TABLE Admin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE Members (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    dateNaissance DATE NOT NULL,
    sport VARCHAR(50) NOT NULL
);

CREATE TABLE Entraineurs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    specialite VARCHAR(50) NOT NULL
);

CREATE TABLE Seances (
    id INT PRIMARY KEY AUTO_INCREMENT,
    member_id INT NOT NULL,
    entraineur_id INT NOT NULL,
    dateHeure DATETIME NOT NULL,
    FOREIGN KEY (member_id) REFERENCES Members(id) ON DELETE CASCADE,
    FOREIGN KEY (entraineur_id) REFERENCES Entraineurs(id) ON DELETE CASCADE
);


SELECT * FROM Admin;
SELECT * FROM Members;
SELECT * FROM Entraineurs;
SELECT * FROM Seances;

SHOW TABLES;