/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-03-14 15:21:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addSeance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1740564824324L));
    _jspx_dependants.put("jar:file:/C:/Users/ENAA/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664449878000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SportFlow - Add Séance</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }\r\n");
      out.write("        @keyframes bounceIn { 0% { transform: scale(0.8); opacity: 0; } 60% { transform: scale(1.05); opacity: 1; } 100% { transform: scale(1); } }\r\n");
      out.write("        @keyframes rotateBorder { 0% { border-color: #FFD700; } 50% { border-color: #e6c200; } 100% { border-color: #FFD700; } }\r\n");
      out.write("        body {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(0, 0, 0, 0.7), rgba(26, 26, 26, 0.7)),\r\n");
      out.write("            url('https://i.pinimg.com/736x/1e/da/48/1eda480b629bcf0bc36fa2c53404b089.jpg') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-family: 'Arial', sans-serif;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar { background: #000000; border-bottom: 4px solid transparent; border-image: linear-gradient(to right, #FFD700, #e6c200) 1; box-shadow: 0 4px 15px rgba(255, 215, 0, 0.2); }\r\n");
      out.write("        .nav-link { transition: color 0.3s ease; }\r\n");
      out.write("        .nav-link:hover { color: #e6c200; }\r\n");
      out.write("        .form-container { background: rgba(0, 0, 0, 0.8); border: 2px solid #FFD700; border-radius: 10px; }\r\n");
      out.write("        .btn { transition: transform 0.3s ease, box-shadow 0.3s ease; }\r\n");
      out.write("        .btn:hover { transform: scale(1.05); box-shadow: 0 0 15px rgba(255, 215, 0, 0.5); }\r\n");
      out.write("        footer { background: rgba(0, 0, 0, 0.9); border-top: 1px solid #FFD700; animation: fadeIn 2s ease-in forwards; }\r\n");
      out.write("        input { background: #333; color: #fff; border: 1px solid #FFD700; border-radius: 5px; padding: 0.5rem; width: 100%; }\r\n");
      out.write("        label { color: #FFD700; font-weight: bold; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navigation Bar -->\r\n");
      out.write("<nav class=\"navbar p-4 flex justify-between items-center fixed top-0 w-full z-10\">\r\n");
      out.write("    <div class=\"text-4xl font-extrabold text-[#FFD700] tracking-wide\">SportFlow Admin</div>\r\n");
      out.write("    <div class=\"space-x-8\">\r\n");
      out.write("        <a href=\"MemberServlet\" class=\"nav-link text-[#FFD700] text-xl font-semibold\">Manage Members</a>\r\n");
      out.write("        <a href=\"EntraineurServlet\" class=\"nav-link text-[#FFD700] text-xl font-semibold\">Manage Entraineurs</a>\r\n");
      out.write("        <a href=\"SeanceServlet\" class=\"nav-link text-[#FFD700] text-xl font-semibold\">Manage Séances</a>\r\n");
      out.write("        <a href=\"Logout\" class=\"nav-link text-[#FFD700] text-xl font-semibold hover:text-red-500\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Body -->\r\n");
      out.write("<main class=\"flex-grow py-20 mt-16\">\r\n");
      out.write("    <div class=\"text-center mb-12\">\r\n");
      out.write("        <h1 class=\"text-5xl font-extrabold text-[#FFD700] mb-6 animate-fade-in\">Add New Séance</h1>\r\n");
      out.write("        <p class=\"text-xl text-gray-300 animate-fade-in\" style=\"animation-delay: 0.5s;\">Schedule a new session by filling in the details below.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-container mx-auto max-w-lg p-6\">\r\n");
      out.write("        <form action=\"AddSeanceServlet\" method=\"post\">\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"memberId\" class=\"block mb-2\">Member ID</label>\r\n");
      out.write("                <input type=\"number\" id=\"memberId\" name=\"memberId\" required min=\"1\" placeholder=\"Enter Member ID\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"entraineurId\" class=\"block mb-2\">Trainer ID</label>\r\n");
      out.write("                <input type=\"number\" id=\"entraineurId\" name=\"entraineurId\" required min=\"1\" placeholder=\"Enter Trainer ID\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"dateHeure\" class=\"block mb-2\">Date and Time</label>\r\n");
      out.write("                <input type=\"datetime-local\" id=\"dateHeure\" name=\"dateHeure\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"flex justify-end space-x-4\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn bg-[#FFD700] text-black font-semibold py-2 px-4 rounded-lg\">Add Séance</button>\r\n");
      out.write("                <a href=\"SeanceServlet\" class=\"btn bg-gray-500 text-white font-semibold py-2 px-4 rounded-lg\">Cancel</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"p-6 text-center text-gray-400\">\r\n");
      out.write("    <p>© 2025 SportFlow. Created by <span class=\"text-[#FFD700] font-semibold\">Lahcen Ait Maskour</span>.\r\n");
      out.write("        Images by <a href=\"https://unsplash.com\" class=\"text-[#FFD700] hover:text-[#e6c200]\">Unsplash</a>.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- Security Check -->\r\n");

    jakarta.servlet.http.HttpSession sessionCheck = request.getSession(false);
    if (sessionCheck == null || sessionCheck.getAttribute("user") == null || !"admin".equals(sessionCheck.getAttribute("user"))) {
        response.sendRedirect("login.jsp");
    }

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /addSeance.jsp(72,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(false);
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <p class=\"text-red-500 text-center mt-4\">${errorMessage}</p>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
